// ************  HostPath ************

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deply
  labels:
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fd-pod
  template:
    metadata:
      name: fd-pod
      labels:
        app: fd-pod
    spec:
      volumes:
        - name: cache-volume
          emptyDir: {}
        - name: test-volume
          hostPath:
            path: /tmp
            type: Directory
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - name: cache-volume
              mountPath: /usr/share/nginx/html
            - name: test-volume
              mountPath: /tmp/e00049              
        -  name: ubuntu
           image: ubuntu
           command: [ "/bin/sh", "-c", "date >> /test/index.html && sleep 10"]
           volumeMounts:
            - name: cache-volume
              mountPath: /test
			  
---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-svc
  labels:
    env: prod
spec: 
  selector:
    app: fd-pod
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    			  
