apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deploy
  labels:
    app: nginx-app
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata: 
      name: nginx-deploy
      labels: 
        app: nginx-app
    spec:
      volumes:
      - name: nginx-data
        hostPath: 
          path: /tmp/nginx-data/            
          type: Directory
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80        
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: nginx-data
            
---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-svc
  labels: 
    app: nginx-svc
spec: 
  type: NodePort
  selector: 
    app: nginx-app
  ports:
    - port: 80
      targetPort: 80 
        
        
