apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deploy
  labels:
    app: nginx-flask
spec: 
  replicas: 3
  selector: 
    matchLabels:
      app: nginx-pod
  template:
    metadata: 
      name: nginx-pod
      labels: 
        app: nginx-pod
    spec:
      volumes:
      - name: nginx-data
        hostPath: /tmp/nginx-content
      containers:
        - name: ubuntu
          image: ubuntu
          command: ["/bin/bash", "-c", "date >> /mnt/nginx-data && sleep 500"]
          volumeMount:
          - name: nginx-data
            mountPath: /mnt/nginx-data
        - name: nginx-container
          image: nginx
          ports:
          - conatinerPort: 80
          volumeMount:
          - name: nginx-data
            mountPath: /usr/local/nginx/html
            
