---
apiVersion: v1
kind: Pod
metadata:
  labels:
  name: app02-dual-container
spec:
  containers:
  - image: nginx
    name: container1
  - image: busybox
    name: container2
    command: ["sh", "-c", "while true; do date >> /vol/date.log; sleep 1; done"]   
