apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
  namespace: e00049  
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/volumes/data"
  storageClassName: manual-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  namespace: e00049  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: manual-pv
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: e00049  
data:
  nginx.conf: |
    # Nginx configuration file
    server {
      listen 80;
      server_name example.com;
      location / {
        root /usr/share/nginx/html;
        index index.html;
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
  namespace: e00049  
type: Opaque
data:
  username: YWRtaW4=
  password: YWRtaW4=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: e00049
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-worker-01  
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80          
          volumeMounts:          
          - name: config-volume
            mountPath: /etc/nginx/conf.d
          - name: secret-volume
            mountPath: /etc/nginx/secrets
          resources:
            requests:
              cpu: "1"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"          
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10            
      volumes:
       - name: config-volume
         configMap:
           name: nginx-configmap
       - name: secret-volume
         secret:
           secretName: nginx-secret
      #    volumeMounts:
      #    - name: nginx-storage
      #      mountPath: /usr/share/nginx/html
      # volumes:
      # - name: nginx-storage
      #   persistentVolumeClaim:
      #     claimName: nginx-pvc            
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: e00049  
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
